[package]
name = "dab-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.serenity]
version = "*"
features = ["http", "builder", "client", "gateway", "cache", "temp_cache"]

[dependencies.tokio]
version = "*"
features = ["rt", "rt-multi-thread", "macros"]

[dependencies]
songbird = "*"
mysql_async = "*"
url = "*"
config = "*"
log = "*"
env_logger = "*"
async-trait = "*"
async-std = "*"
concurrent_queue = "*"
chashmap = "*"