success = Das hat funktioniert! 🎉
fail = Das hat nicht funktioniert... 😟
file-too-large = Das ist mir zu groß! 🥵
download-failed = Der Download ist abgekackt... 😟
bad-url = Mit dieser URL kann ich nix anfangen. 🤔
duration-exceeded = Das dauert mir zu lange! 🙄
data-unreadable = Diese Daten kann ich nicht entziffern. 🧐
internal-error = Hoppla! Es ist ein interner Fehler aufgetreten... 🤕
only-in-guilds = Das funktioniert nur auf Servern! ☝
missing-permissions = Wer denkst du wer du bist? 👿
