base = Modify your chime
base-clear = Clear your chime
base-set = Set your chime
base-set-file = Set your chime from a file
base-set-file-attachment = Uploads a file as your chime
base-set-url = Set your chime from an URL
base-set-url-link = Downloads a file as your chime
base-admin = Bot configuration
base-admin-forbid = Set a role whose users chimes are not played
base-admin-forbid-role = The single role to blacklist