success = Success! 🎉
fail = That did not work... 😟
file-too-large = Thats too big for me! 🥵
download-failed = Download failed... 😟
bad-url = That URL does not work for me. 🤔
duration-exceeded = Thats too long for me! 😳
data-unreadable = I can't read this data. 🧐
internal-error = Whoops! An internal error occurred... 🤕
only-in-guilds = This only works in guilds! ☝
missing-permissions = Who do you think you are? 👿
